export enum Configuration {
  PORT = 'PORT',
  URL = 'URL',
  JWT_SECRET = 'JWT_SECRET',
  APP_PREFIX = 'APP_PREFIX',
  DOCUMENTATION_TITLE = 'DOCUMENTATION_TITLE',
  DOCUMENTATION_DESCRIPTION = 'DOCUMENTATION_DESCRIPTION',
  DOCUMENTATION_VERSION = 'DOCUMENTATION_VERSION',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_SECRET = 'GOOGLE_SECRET',
  CALLBACK_URL = 'CALLBACK_URL',
}
